name: Remove runs of the cleanup workflow itself
  uses: actions/github-script@v4 # https://github.com/actions/github-script
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const pages = 5;

      let runs_to_delete = [];

      for (let page = 0; page < pages; page += 1) {
        let response = await github.actions.listWorkflowRuns({
          owner: context.repo.owner,
          page: page,
          per_page: 100,
          repo: context.repo.repo,
          workflow_id: 'workflow_run_pruner.yml'
        });

        if (response.data.workflow_runs.length > 0) {
          for (const run of response.data.workflow_runs) {
              runs_to_delete.push([run.id, run.name]);
          }
        }
      }

      for (const run of runs_to_delete) {
        console.log(`[Deleting] Run id ${run[0]} of '${run[1]}'.`);
        try {
          await github.actions.deleteWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: run[0]
          });
        } catch (error) {
          // ignore errors
        }
      }
